/**
 * @fileoverview Type definitions for the loop module
 */

/**
 * Available preset loop prompts
 */
export type LoopPreset =
	| 'default'
	| 'test-coverage'
	| 'linting'
	| 'duplication'
	| 'entropy';

/** Context passed to preset factory functions so projectRoot is injected at call time */
export type PresetCtx = { projectRoot: string };

/**
 * Per-iteration summary of tool-call activity (emitted at iteration end in trace mode).
 */
export interface LoopToolCallSummary {
	/** Tool name (e.g. "Bash", "Edit", "Read") */
	name: string;
	/** Number of times this tool was invoked during the iteration */
	count: number;
}

/**
 * Per-iteration token-usage snapshot, sourced from the stream-json `result`
 * event's `usage` field (emitted at iteration end in trace mode).
 *
 * Each loop iteration spawns a fresh `claude -p` session, so this is the
 * total spend for that iteration - there is no carry-over context across
 * iterations to subtract.
 */
export interface LoopTokenUsage {
	/** Uncached input (prompt) tokens billed for the iteration */
	inputTokens: number;
	/** Output (completion) tokens generated by the model */
	outputTokens: number;
	/** Tokens written to the prompt cache, if any */
	cacheCreationInputTokens?: number;
	/** Tokens read from the prompt cache, if any */
	cacheReadInputTokens?: number;
	/** Sum of input + output + cache creation + cache read tokens */
	totalTokens: number;
}

/**
 * Output callbacks for loop execution.
 * These allow the caller (CLI/MCP) to handle presentation while
 * the service stays focused on business logic.
 *
 * Callback modes (controlled by `LoopConfig.verbose` and `LoopConfig.trace`):
 * - `onLoopStart`, `onLoopEnd`, `onIterationStart`, `onIterationEnd`, `onError`, `onStderr`: all modes
 * - `onText`, `onToolUse`: VERBOSE or TRACE mode
 * - `onOutput`: NORMAL mode only (no --verbose, no --trace)
 * - `onPromptSent`, `onToolInput`, `onToolResult`, `onIterationSummary`: TRACE mode only
 *
 * Presentation layers decide whether to render `onLoopStart`/`onLoopEnd` —
 * the CLI prints them only when verbose so quiet runs stay quiet.
 */
export interface LoopOutputCallbacks {
	/** Called once when the loop begins, before any iteration runs (all modes) */
	onLoopStart?: (startedAt: Date, totalIterations: number) => void;
	/** Called at the start of each iteration (all modes) */
	onIterationStart?: (iteration: number, total: number) => void;
	/** Called when Claude outputs text (VERBOSE or TRACE mode) */
	onText?: (text: string) => void;
	/** Called when Claude invokes a tool, with just the name (VERBOSE or TRACE mode) */
	onToolUse?: (toolName: string) => void;
	/** Called when an error occurs (all modes) */
	onError?: (message: string, severity?: 'warning' | 'error') => void;
	/** Called for stderr output (all modes) */
	onStderr?: (iteration: number, text: string) => void;
	/** Called when non-verbose iteration completes with output (NORMAL mode only) */
	onOutput?: (output: string) => void;
	/** Called at the end of each iteration with the result (all modes) */
	onIterationEnd?: (iteration: LoopIteration) => void;
	/** Called once when the loop finishes (success, early exit, or error) */
	onLoopEnd?: (finishedAt: Date, totalDuration: number) => void;

	// ---- Trace-only callbacks ----

	/** Called once per iteration with the full prompt sent to the LLM (TRACE mode only) */
	onPromptSent?: (iteration: number, prompt: string) => void;
	/** Called with the input parameters for each tool invocation (TRACE mode only) */
	onToolInput?: (toolName: string, input: unknown) => void;
	/** Called with the result content returned to a tool invocation (TRACE mode only) */
	onToolResult?: (toolName: string | undefined, result: unknown) => void;
	/**
	 * Called at the end of each iteration with an aggregated summary (TRACE mode only).
	 *
	 * `tokenUsage` is present when the stream-json `result` event carried a
	 * usage payload; absent for older Claude CLI versions or aborted runs.
	 */
	onIterationSummary?: (
		iteration: number,
		summary: {
			toolCalls: LoopToolCallSummary[];
			finalResult?: string;
			tokenUsage?: LoopTokenUsage;
			totalToolCalls?: number;
			taskMasterToolCalls?: number;
			writeToolCalls?: number;
			nonWriteToolCalls?: number;
			estimatedContext?: number;
			percentOf1M?: number;
			modelId?: string;
		}
	) => void;
}

/**
 * Verbosity level for loop output.
 * 'none' = silent; 'verbose' = real-time streaming; 'trace' = verbose + debug events + progress file writes.
 */
export type LoopTraceLevel = 'none' | 'verbose' | 'trace';

/**
 * Configuration options for a loop execution
 */
export interface LoopConfig {
	/** Number of iterations to run */
	iterations: number;
	/** Preset name or custom prompt file path */
	prompt: LoopPreset | string;
	/** Path to the progress file */
	progressFile: string;
	/** Seconds to sleep between iterations */
	sleepSeconds: number;
	/** Tag context to operate on (optional) */
	tag?: string;
	/** Run Claude in Docker sandbox mode (default: false) */
	sandbox?: boolean;
	/**
	 * Include full Claude output in iteration results (default: false)
	 *
	 * When true: `LoopIteration.output` will contain full stdout+stderr text
	 * When false: `LoopIteration.output` will be undefined (saves memory)
	 *
	 * Can be combined with `verbose=true` to both display and capture output.
	 * Note: Output can be large (up to 50MB per iteration).
	 */
	includeOutput?: boolean;
	/**
	 * Verbosity level for loop output (default: 'none').
	 * 'verbose' streams Claude's work in real-time (NOT compatible with sandbox=true).
	 * 'trace' additionally emits onPromptSent, onToolInput, onToolResult, onIterationSummary
	 * and writes trace details to the progress file.
	 * NOT compatible with sandbox=true.
	 */
	traceLevel?: LoopTraceLevel;
	/**
	 * Brief title describing the current initiative/goal (optional)
	 *
	 * If provided, included in the progress file header to give Claude
	 * context about the bigger picture across iterations.
	 * Example: "Implement streaming output for loop command"
	 */
	brief?: string;
	/**
	 * Persist the claude session for each iteration (default: false).
	 *
	 * When false (the default), `--no-session-persistence` is appended to every
	 * claude invocation so loop iterations do not accumulate in `claude --resume`
	 * history. Set to true to allow session persistence (e.g., for debugging a
	 * specific iteration with `claude --resume`).
	 */
	sessionPersistence?: boolean;
	/**
	 * Output callbacks for presentation layer (CLI/MCP).
	 * If not provided, the service runs silently (no console output).
	 */
	callbacks?: LoopOutputCallbacks;
}

/**
 * Result of a single loop iteration
 */
export interface LoopIteration {
	/** Iteration number (1-indexed) */
	iteration: number;
	/** ID of the task worked on (if any) */
	taskId?: string;
	/** Status of this iteration */
	status: 'success' | 'blocked' | 'error' | 'complete';
	/** Optional message describing the result */
	message?: string;
	/** Duration of this iteration in milliseconds */
	duration?: number;
	/**
	 * Full Claude output text
	 *
	 * ONLY present when `LoopConfig.includeOutput=true`.
	 * Contains concatenated stdout and stderr from Claude CLI execution.
	 * May include ANSI color codes and tool call output.
	 * Can be large - use `includeOutput=false` to save memory.
	 */
	output?: string;
}

/**
 * Overall result of a loop execution
 */
export interface LoopResult {
	/** Array of iteration results */
	iterations: LoopIteration[];
	/** Total number of iterations executed */
	totalIterations: number;
	/** Number of tasks completed successfully */
	tasksCompleted: number;
	/** Final status of the loop */
	finalStatus: 'all_complete' | 'max_iterations' | 'blocked' | 'error';
	/** Error message when finalStatus is 'error' (optional) */
	errorMessage?: string;
	/** ISO-8601 timestamp when the loop started */
	startedAt?: string;
	/** ISO-8601 timestamp when the loop finished */
	finishedAt?: string;
	/** Total wall-clock duration of the loop in milliseconds (includes inter-iteration sleeps) */
	totalDuration?: number;
}
