/**
 * Tests for GitHubPRService
 */

import { describe, it, expect, beforeEach } from 'vitest';
import type { WorkflowContext } from '../../workflow/types.js';
import { GitHubPRService, type PRClusterInput } from './github-pr.service.js';

describe('GitHubPRService', () => {
	let service: GitHubPRService;
	const projectRoot = '/test/project';

	beforeEach(() => {
		service = new GitHubPRService(projectRoot, 'main');
	});

	describe('createPR - dry run mode', () => {
		it('should validate and preview PR creation in dry-run mode', async () => {
			const cluster: PRClusterInput = {
				clusterId: 'cluster-1',
				branchName: 'feature/test-branch',
				taskId: 'TAS-123',
				tag: 'test-tag'
			};

			const result = await service.createPR({
				cluster,
				dryRun: true
			});

			expect(result.success).toBe(true);
			expect(result.dryRun).toBe(true);
			expect(result.clusterId).toBe('cluster-1');
			expect(result.prUrl).toBeUndefined();
		});

		it('should generate PR title with conventional commit format', async () => {
			const cluster: PRClusterInput = {
				clusterId: 'cluster-1',
				branchName: 'feature/test',
				taskId: 'TAS-123',
				tag: 'auth'
			};

			const result = await service.createPR({
				cluster,
				dryRun: true
			});

			expect(result.success).toBe(true);
			expect(result.title).toBe(
				'feat(auth): implement cluster cluster-1 [TAS-123]'
			);
			expect(result.title).toMatch(/^feat\(/);
			expect(result.title).toContain('[TAS-123]');
		});

		it('should generate PR body with cluster metadata', async () => {
			const cluster: PRClusterInput = {
				clusterId: 'cluster-1',
				branchName: 'feature/test',
				taskId: 'TAS-123',
				commits: ['abc123', 'def456']
			};

			const workflowContext: WorkflowContext = {
				taskId: 'TAS-123',
				subtasks: [
					{
						id: 'sub-1',
						title: 'Implement feature',
						status: 'completed',
						attempts: 1
					},
					{
						id: 'sub-2',
						title: 'Add tests',
						status: 'in-progress',
						attempts: 1
					}
				],
				currentSubtaskIndex: 1,
				errors: [],
				metadata: {},
				lastTestResults: {
					total: 10,
					passed: 8,
					failed: 2,
					skipped: 0,
					phase: 'GREEN'
				}
			};

			const result = await service.createPR({
				cluster,
				workflowContext,
				dryRun: true
			});

			expect(result.success).toBe(true);
			expect(result.body).toBeDefined();

			// Subtasks section
			expect(result.body).toContain('## Subtasks Completed');
			expect(result.body).toContain('[x] Implement feature');
			expect(result.body).toContain('[ ] Add tests');
			expect(result.body).toContain('1/2 subtasks completed');

			// Test results section
			expect(result.body).toContain('## Test Results');
			expect(result.body).toContain('**Phase**: GREEN');
			expect(result.body).toContain('**Total**: 10');
			expect(result.body).toContain('**Passed**');
			expect(result.body).toContain('**Failed**');

			// Commit history section
			expect(result.body).toContain('## Commit History');
			expect(result.body).toContain('abc123');
			expect(result.body).toContain('def456');
			expect(result.body).toContain('**Total Commits**: 2');

			// Related links section
			expect(result.body).toContain('`TAS-123`');

			// Footer
			expect(result.body).toContain('Generated by TaskMaster Autopilot');
		});
	});

	describe('validation', () => {
		it('should fail validation if clusterId is missing', async () => {
			const cluster: PRClusterInput = {
				clusterId: '',
				branchName: 'feature/test'
			};

			const result = await service.createPR({
				cluster,
				dryRun: true
			});

			expect(result.success).toBe(false);
			expect(result.error).toContain('Cluster ID is required');
		});

		it('should fail validation if branchName is missing', async () => {
			const cluster: PRClusterInput = {
				clusterId: 'cluster-1',
				branchName: ''
			};

			const result = await service.createPR({
				cluster,
				dryRun: true
			});

			expect(result.success).toBe(false);
			expect(result.error).toContain('Branch name is required');
		});
	});

	describe('cluster PR mapping', () => {
		it('should store and retrieve cluster PR mappings', () => {
			const mapping = {
				clusterId: 'cluster-1',
				prUrl: 'https://github.com/org/repo/pull/123',
				prNumber: 123,
				branchName: 'feature/test',
				createdAt: new Date().toISOString()
			};

			service.setClusterPRMapping(mapping);

			const retrieved = service.getClusterPRMapping('cluster-1');
			expect(retrieved).toEqual(mapping);
		});

		it('should return undefined for non-existent cluster', () => {
			const retrieved = service.getClusterPRMapping('non-existent');
			expect(retrieved).toBeUndefined();
		});

		it('should return all mappings', () => {
			const mapping1 = {
				clusterId: 'cluster-1',
				prUrl: 'https://github.com/org/repo/pull/123',
				prNumber: 123,
				branchName: 'feature/test-1',
				createdAt: new Date().toISOString()
			};

			const mapping2 = {
				clusterId: 'cluster-2',
				prUrl: 'https://github.com/org/repo/pull/124',
				prNumber: 124,
				branchName: 'feature/test-2',
				createdAt: new Date().toISOString()
			};

			service.setClusterPRMapping(mapping1);
			service.setClusterPRMapping(mapping2);

			const allMappings = service.getAllClusterPRMappings();
			expect(allMappings).toHaveLength(2);
			expect(allMappings).toContainEqual(mapping1);
			expect(allMappings).toContainEqual(mapping2);
		});

		it('should clear all mappings', () => {
			const mapping = {
				clusterId: 'cluster-1',
				prUrl: 'https://github.com/org/repo/pull/123',
				prNumber: 123,
				branchName: 'feature/test',
				createdAt: new Date().toISOString()
			};

			service.setClusterPRMapping(mapping);
			expect(service.getAllClusterPRMappings()).toHaveLength(1);

			service.clearMappings();
			expect(service.getAllClusterPRMappings()).toHaveLength(0);
		});
	});

	describe('PR title generation', () => {
		it('should generate title with task ID', async () => {
			const cluster: PRClusterInput = {
				clusterId: 'cluster-1',
				branchName: 'feature/test',
				taskId: 'TAS-123',
				tag: 'auth'
			};

			const result = await service.createPR({
				cluster,
				dryRun: true
			});

			expect(result.success).toBe(true);
			expect(result.title).toContain('[TAS-123]');
			expect(result.title).toBe(
				'feat(auth): implement cluster cluster-1 [TAS-123]'
			);
		});

		it('should generate title without task ID', async () => {
			const cluster: PRClusterInput = {
				clusterId: 'cluster-1',
				branchName: 'feature/test',
				tag: 'api'
			};

			const result = await service.createPR({
				cluster,
				dryRun: true
			});

			expect(result.success).toBe(true);
			expect(result.title).toBe('feat(api): implement cluster cluster-1');
			expect(result.title).not.toContain('[');
		});

		it('should use custom title if provided', async () => {
			const cluster: PRClusterInput = {
				clusterId: 'cluster-1',
				branchName: 'feature/test'
			};

			const customTitle = 'feat(custom): custom PR title';

			const result = await service.createPR({
				cluster,
				title: customTitle,
				dryRun: true
			});

			expect(result.success).toBe(true);
			expect(result.title).toBe(customTitle);
		});
	});

	describe('PR body generation', () => {
		it('should include subtasks in body', async () => {
			const cluster: PRClusterInput = {
				clusterId: 'cluster-1',
				branchName: 'feature/test'
			};

			const workflowContext: WorkflowContext = {
				taskId: 'TAS-123',
				subtasks: [
					{
						id: 'sub-1',
						title: 'Task 1',
						status: 'completed',
						attempts: 1
					},
					{
						id: 'sub-2',
						title: 'Task 2',
						status: 'pending',
						attempts: 0
					}
				],
				currentSubtaskIndex: 0,
				errors: [],
				metadata: {}
			};

			const result = await service.createPR({
				cluster,
				workflowContext,
				dryRun: true
			});

			expect(result.success).toBe(true);
			expect(result.body).toBeDefined();
			expect(result.body).toContain('## Subtasks Completed');
			expect(result.body).toContain('[x] Task 1');
			expect(result.body).toContain('[ ] Task 2');
			expect(result.body).toContain('1/2 subtasks completed');
		});

		it('should include test results in body', async () => {
			const cluster: PRClusterInput = {
				clusterId: 'cluster-1',
				branchName: 'feature/test'
			};

			const workflowContext: WorkflowContext = {
				taskId: 'TAS-123',
				subtasks: [],
				currentSubtaskIndex: 0,
				errors: [],
				metadata: {},
				lastTestResults: {
					total: 15,
					passed: 15,
					failed: 0,
					skipped: 0,
					phase: 'GREEN'
				}
			};

			const result = await service.createPR({
				cluster,
				workflowContext,
				dryRun: true
			});

			expect(result.success).toBe(true);
			expect(result.body).toBeDefined();
			expect(result.body).toContain('## Test Results');
			expect(result.body).toContain('**Phase**: GREEN');
			expect(result.body).toContain('**Total**: 15');
			expect(result.body).toContain('15');
			expect(result.body).toContain('**Pass Rate**: 100.0%');
		});

		it('should use custom body if provided', async () => {
			const cluster: PRClusterInput = {
				clusterId: 'cluster-1',
				branchName: 'feature/test'
			};

			const customBody = '## Custom Body\n\nThis is a custom PR body.';

			const result = await service.createPR({
				cluster,
				body: customBody,
				dryRun: true
			});

			expect(result.success).toBe(true);
			expect(result.body).toBe(customBody);
		});
	});
});
