/**
 * Tests for PRBodyFormatter
 */

import { describe, it, expect, beforeEach } from 'vitest';
import {
	PRBodyFormatter,
	type PRBodyFormatterOptions,
	type CommitInfo,
	type TestPhaseResult
} from './pr-body-formatter.js';
import type { WorkflowContext } from '../../workflow/types.js';

describe('PRBodyFormatter', () => {
	let formatter: PRBodyFormatter;

	beforeEach(() => {
		formatter = new PRBodyFormatter();
	});

	describe('format - full PR body', () => {
		it('should format a complete PR body with all sections', () => {
			const workflowContext: WorkflowContext = {
				taskId: 'TAS-123',
				subtasks: [
					{
						id: 'sub-1',
						title: 'Implement feature',
						status: 'completed',
						attempts: 1
					},
					{
						id: 'sub-2',
						title: 'Add tests',
						status: 'completed',
						attempts: 2
					}
				],
				currentSubtaskIndex: 1,
				errors: [],
				metadata: {},
				lastTestResults: {
					total: 10,
					passed: 10,
					failed: 0,
					skipped: 0,
					phase: 'GREEN'
				}
			};

			const commits: CommitInfo[] = [
				{
					sha: 'abc123def456',
					message: 'feat(auth): implement user authentication',
					author: 'John Doe',
					timestamp: '2024-01-15T10:00:00Z'
				},
				{
					sha: 'def456ghi789',
					message: 'test(auth): add authentication tests',
					author: 'John Doe',
					timestamp: '2024-01-15T11:00:00Z'
				}
			];

			const options: PRBodyFormatterOptions = {
				workflowContext,
				taskTitle: 'Add user authentication',
				taskDescription: 'Implement JWT-based authentication for API',
				commits,
				branchName: 'feature/auth',
				tag: 'auth',
				taskId: 'TAS-123',
				runStartTime: '2024-01-15T10:00:00Z',
				runEndTime: '2024-01-15T12:00:00Z',
				coveragePercent: 85.5
			};

			const body = formatter.format(options);

			expect(body).toContain('## Summary');
			expect(body).toContain('Add user authentication');
			expect(body).toContain('## Subtasks Completed');
			expect(body).toContain('Implement feature');
			expect(body).toContain('## Test Results');
			expect(body).toContain('## Commit History');
			expect(body).toContain('## Run Metrics');
			expect(body).toContain('## Related Links');
			expect(body).toContain('🤖 Generated by TaskMaster Autopilot');
		});

		it('should format PR body with selective sections', () => {
			const options: PRBodyFormatterOptions = {
				taskTitle: 'Simple feature',
				taskId: 'TAS-456',
				sections: {
					summary: true,
					subtasks: false,
					testResults: false,
					commits: false,
					runMetrics: false,
					links: true
				}
			};

			const body = formatter.format(options);

			expect(body).toContain('## Summary');
			expect(body).toContain('## Related Links');
			expect(body).not.toContain('## Subtasks');
			expect(body).not.toContain('## Test Results');
			expect(body).not.toContain('## Commit History');
		});
	});

	describe('formatSummary', () => {
		it('should format summary with title and description', () => {
			const options: PRBodyFormatterOptions = {
				taskTitle: 'Add authentication',
				taskDescription: 'Implement JWT authentication for API endpoints'
			};

			const body = formatter.format(options);

			expect(body).toContain('## Summary');
			expect(body).toContain('Add authentication');
			expect(body).toContain('Implement JWT authentication');
		});

		it('should format summary with only title', () => {
			const options: PRBodyFormatterOptions = {
				taskTitle: 'Add authentication'
			};

			const body = formatter.format(options);

			expect(body).toContain('## Summary');
			expect(body).toContain('This PR implements: Add authentication');
		});
	});

	describe('formatSubtasks', () => {
		it('should format subtasks with checkboxes', () => {
			const workflowContext: WorkflowContext = {
				taskId: 'TAS-123',
				subtasks: [
					{
						id: 'sub-1',
						title: 'Task 1',
						status: 'completed',
						attempts: 1
					},
					{
						id: 'sub-2',
						title: 'Task 2',
						status: 'in-progress',
						attempts: 1
					},
					{
						id: 'sub-3',
						title: 'Task 3',
						status: 'pending',
						attempts: 0
					}
				],
				currentSubtaskIndex: 1,
				errors: [],
				metadata: {}
			};

			const options: PRBodyFormatterOptions = {
				workflowContext
			};

			const body = formatter.format(options);

			expect(body).toContain('## Subtasks Completed');
			expect(body).toContain('- [x] Task 1');
			expect(body).toContain('- [ ] Task 2');
			expect(body).toContain('- [ ] Task 3');
			expect(body).toContain('Progress**: 1/3');
		});

		it('should show attempt count for retried subtasks', () => {
			const workflowContext: WorkflowContext = {
				taskId: 'TAS-123',
				subtasks: [
					{
						id: 'sub-1',
						title: 'Difficult task',
						status: 'completed',
						attempts: 3
					}
				],
				currentSubtaskIndex: 0,
				errors: [],
				metadata: {}
			};

			const options: PRBodyFormatterOptions = {
				workflowContext
			};

			const body = formatter.format(options);

			expect(body).toContain('Difficult task (3 attempts)');
		});
	});

	describe('formatTestResults', () => {
		it('should format latest test results', () => {
			const workflowContext: WorkflowContext = {
				taskId: 'TAS-123',
				subtasks: [],
				currentSubtaskIndex: 0,
				errors: [],
				metadata: {},
				lastTestResults: {
					total: 20,
					passed: 18,
					failed: 2,
					skipped: 0,
					phase: 'GREEN'
				}
			};

			const options: PRBodyFormatterOptions = {
				workflowContext
			};

			const body = formatter.format(options);

			expect(body).toContain('## Test Results');
			expect(body).toContain('Latest Test Run');
			expect(body).toContain('Phase**: GREEN');
			expect(body).toContain('Total**: 20');
			expect(body).toContain('Passed**: ✅ 18');
			expect(body).toContain('Failed**: ❌ 2');
			expect(body).toContain('Pass Rate**: 90.0%');
		});

		it('should format TDD cycle history', () => {
			const testResults: TestPhaseResult[] = [
				{
					phase: 'RED',
					total: 5,
					passed: 0,
					failed: 5,
					skipped: 0
				},
				{
					phase: 'GREEN',
					total: 5,
					passed: 5,
					failed: 0,
					skipped: 0
				}
			];

			const options: PRBodyFormatterOptions = {
				testResults
			};

			const body = formatter.format(options);

			expect(body).toContain('## Test Results');
			expect(body).toContain('TDD Cycle History');
			expect(body).toContain('🔴 RED');
			expect(body).toContain('🟢 GREEN');
		});

		it('should format coverage percentage', () => {
			const options: PRBodyFormatterOptions = {
				coveragePercent: 87.3
			};

			const body = formatter.format(options);

			expect(body).toContain('## Test Results');
			expect(body).toContain('Coverage');
			expect(body).toContain('87.3%');
		});
	});

	describe('formatCommits', () => {
		it('should format commit history', () => {
			const commits: CommitInfo[] = [
				{
					sha: 'abc123def456',
					message: 'feat(auth): implement authentication',
					author: 'John Doe',
					timestamp: '2024-01-15T10:00:00Z'
				},
				{
					sha: 'def456ghi789',
					message: 'test(auth): add tests',
					author: 'Jane Smith'
				},
				{
					sha: 'ghi789jkl012',
					message: 'docs(auth): update documentation'
				}
			];

			const options: PRBodyFormatterOptions = {
				commits
			};

			const body = formatter.format(options);

			expect(body).toContain('## Commit History');
			expect(body).toContain('abc123d');
			expect(body).toContain('feat(auth): implement authentication');
			expect(body).toContain('by John Doe');
			expect(body).toContain('def456g');
			expect(body).toContain('by Jane Smith');
			expect(body).toContain('Total Commits**: 3');
		});
	});

	describe('formatRunMetrics', () => {
		it('should format run duration', () => {
			const options: PRBodyFormatterOptions = {
				runStartTime: '2024-01-15T10:00:00Z',
				runEndTime: '2024-01-15T12:30:45Z'
			};

			const body = formatter.format(options);

			expect(body).toContain('## Run Metrics');
			expect(body).toContain('Duration**: 2h 30m 45s');
		});

		it('should format branch and tag', () => {
			const options: PRBodyFormatterOptions = {
				branchName: 'feature/auth',
				tag: 'sprint-1'
			};

			const body = formatter.format(options);

			expect(body).toContain('## Run Metrics');
			expect(body).toContain('Branch**: `feature/auth`');
			expect(body).toContain('Tag**: `sprint-1`');
		});
	});

	describe('formatLinks', () => {
		it('should format task links', () => {
			const options: PRBodyFormatterOptions = {
				taskId: 'TAS-123'
			};

			const body = formatter.format(options);

			expect(body).toContain('## Related Links');
			expect(body).toContain('Task ID**: `TAS-123`');
		});
	});

	describe('formatMinimal', () => {
		it('should format minimal PR body', () => {
			const body = formatter.formatMinimal({
				taskId: 'TAS-123',
				taskTitle: 'Quick fix',
				branchName: 'hotfix/bug'
			});

			expect(body).toContain('## Summary');
			expect(body).toContain('Quick fix');
			expect(body).toContain('Task ID**: `TAS-123`');
			expect(body).toContain('Branch**: `hotfix/bug`');
			expect(body).toContain('🤖 Generated by TaskMaster Autopilot');
		});

		it('should format minimal body with defaults', () => {
			const body = formatter.formatMinimal({});

			expect(body).toContain('## Summary');
			expect(body).toContain('Implementation changes for this task');
			expect(body).toContain('🤖 Generated by TaskMaster Autopilot');
		});
	});

	describe('edge cases', () => {
		it('should handle empty options gracefully', () => {
			const body = formatter.format({});

			expect(body).toContain('🤖 Generated by TaskMaster Autopilot');
			expect(body).toBeTruthy();
		});

		it('should handle zero test results', () => {
			const workflowContext: WorkflowContext = {
				taskId: 'TAS-123',
				subtasks: [],
				currentSubtaskIndex: 0,
				errors: [],
				metadata: {},
				lastTestResults: {
					total: 0,
					passed: 0,
					failed: 0,
					skipped: 0,
					phase: 'RED'
				}
			};

			const options: PRBodyFormatterOptions = {
				workflowContext
			};

			const body = formatter.format(options);

			expect(body).toContain('Pass Rate**: 0%');
		});

		it('should handle empty commits array', () => {
			const options: PRBodyFormatterOptions = {
				commits: []
			};

			const body = formatter.format(options);

			expect(body).not.toContain('## Commit History');
		});
	});
});
