/**
 * PR Body Formatter - Compose comprehensive PR descriptions from run artifacts
 *
 * This service formats PR bodies with:
 * - Task and subtask summaries
 * - Test results and coverage metrics
 * - Commit history
 * - Run metadata and performance metrics
 * - Task ID references
 */

import type { WorkflowContext } from '../../workflow/types.js';

/**
 * Commit information for PR body
 */
export interface CommitInfo {
	sha: string;
	message: string;
	author?: string;
	timestamp?: string;
}

/**
 * Test phase result for PR body
 */
export interface TestPhaseResult {
	phase: 'RED' | 'GREEN';
	total: number;
	passed: number;
	failed: number;
	skipped: number;
	duration?: number;
}

/**
 * Options for PR body formatting
 */
export interface PRBodyFormatterOptions {
	/** Workflow context with run state */
	workflowContext?: WorkflowContext;
	/** Task title */
	taskTitle?: string;
	/** Task description */
	taskDescription?: string;
	/** Array of commits */
	commits?: CommitInfo[];
	/** Test results by phase */
	testResults?: TestPhaseResult[];
	/** Run start timestamp */
	runStartTime?: string;
	/** Run end timestamp */
	runEndTime?: string;
	/** Coverage percentage */
	coveragePercent?: number;
	/** Branch name */
	branchName?: string;
	/** Tag for categorization */
	tag?: string;
	/** Task ID */
	taskId?: string;
	/** Configuration for which sections to include */
	sections?: {
		summary?: boolean;
		subtasks?: boolean;
		testResults?: boolean;
		commits?: boolean;
		runMetrics?: boolean;
		links?: boolean;
	};
}

/**
 * PRBodyFormatter - Pure formatter for PR body generation
 */
export class PRBodyFormatter {
	/**
	 * Format a complete PR body from run artifacts
	 */
	format(options: PRBodyFormatterOptions): string {
		const sections: string[] = [];

		// Default: include all sections
		const includeSection = {
			summary: true,
			subtasks: true,
			testResults: true,
			commits: true,
			runMetrics: true,
			links: true,
			...options.sections
		};

		// Summary section
		if (includeSection.summary) {
			const summarySection = this.formatSummary(options);
			if (summarySection) {
				sections.push(summarySection);
			}
		}

		// Subtasks section
		if (includeSection.subtasks && options.workflowContext?.subtasks) {
			const subtasksSection = this.formatSubtasks(
				options.workflowContext.subtasks
			);
			if (subtasksSection) {
				sections.push(subtasksSection);
			}
		}

		// Test results section
		if (includeSection.testResults) {
			const testSection = this.formatTestResults(options);
			if (testSection) {
				sections.push(testSection);
			}
		}

		// Commits section
		if (includeSection.commits && options.commits) {
			const commitsSection = this.formatCommits(options.commits);
			if (commitsSection) {
				sections.push(commitsSection);
			}
		}

		// Run metrics section
		if (includeSection.runMetrics) {
			const metricsSection = this.formatRunMetrics(options);
			if (metricsSection) {
				sections.push(metricsSection);
			}
		}

		// Links section
		if (includeSection.links) {
			const linksSection = this.formatLinks(options);
			if (linksSection) {
				sections.push(linksSection);
			}
		}

		// Footer
		sections.push('---');
		sections.push('');
		sections.push('🤖 Generated by TaskMaster Autopilot');

		return sections.join('\n');
	}

	/**
	 * Format summary section
	 */
	private formatSummary(options: PRBodyFormatterOptions): string | null {
		const parts: string[] = [];

		parts.push('## Summary');
		parts.push('');

		if (options.taskTitle) {
			parts.push(`**Task**: ${options.taskTitle}`);
			parts.push('');
		}

		if (options.taskDescription) {
			parts.push(options.taskDescription);
			parts.push('');
		} else if (options.taskTitle) {
			parts.push(`This PR implements: ${options.taskTitle}`);
			parts.push('');
		}

		return parts.length > 2 ? parts.join('\n') : null;
	}

	/**
	 * Format subtasks section with checkboxes
	 */
	private formatSubtasks(
		subtasks: Array<{
			id: string;
			title: string;
			status: string;
			attempts: number;
		}>
	): string | null {
		if (subtasks.length === 0) {
			return null;
		}

		const parts: string[] = [];

		parts.push('## Subtasks Completed');
		parts.push('');

		subtasks.forEach((subtask) => {
			const checkbox = subtask.status === 'completed' ? '[x]' : '[ ]';
			const attempts =
				subtask.attempts > 1 ? ` (${subtask.attempts} attempts)` : '';
			parts.push(`- ${checkbox} ${subtask.title}${attempts}`);
		});

		parts.push('');

		// Summary
		const completed = subtasks.filter((s) => s.status === 'completed').length;
		const total = subtasks.length;
		parts.push(`**Progress**: ${completed}/${total} subtasks completed`);
		parts.push('');

		return parts.join('\n');
	}

	/**
	 * Format test results section
	 */
	private formatTestResults(options: PRBodyFormatterOptions): string | null {
		const { testResults, workflowContext, coveragePercent } = options;

		// Try to get test results from either testResults array or workflowContext
		const hasTestData =
			(testResults && testResults.length > 0) ||
			workflowContext?.lastTestResults;

		if (!hasTestData && !coveragePercent) {
			return null;
		}

		const parts: string[] = [];

		parts.push('## Test Results');
		parts.push('');

		// Latest test results
		if (workflowContext?.lastTestResults) {
			const { lastTestResults } = workflowContext;
			parts.push('### Latest Test Run');
			parts.push('');
			parts.push(`- **Phase**: ${lastTestResults.phase}`);
			parts.push(`- **Total**: ${lastTestResults.total}`);
			parts.push(`- **Passed**: ✅ ${lastTestResults.passed}`);
			parts.push(`- **Failed**: ❌ ${lastTestResults.failed}`);
			parts.push(`- **Skipped**: ⏭️ ${lastTestResults.skipped}`);
			parts.push('');

			const passRate =
				lastTestResults.total > 0
					? ((lastTestResults.passed / lastTestResults.total) * 100).toFixed(1)
					: '0';
			parts.push(`**Pass Rate**: ${passRate}%`);
			parts.push('');
		}

		// TDD Phase history
		if (testResults && testResults.length > 0) {
			parts.push('### TDD Cycle History');
			parts.push('');
			parts.push('| Phase | Total | Passed | Failed | Skipped |');
			parts.push('|-------|-------|--------|--------|---------|');

			testResults.forEach((result) => {
				const emoji = result.phase === 'RED' ? '🔴' : '🟢';
				parts.push(
					`| ${emoji} ${result.phase} | ${result.total} | ${result.passed} | ${result.failed} | ${result.skipped} |`
				);
			});

			parts.push('');
		}

		// Coverage
		if (coveragePercent !== undefined) {
			parts.push(`### Coverage`);
			parts.push('');
			parts.push(`**Coverage**: ${coveragePercent.toFixed(1)}%`);
			parts.push('');
		}

		return parts.join('\n');
	}

	/**
	 * Format commits section
	 */
	private formatCommits(commits: CommitInfo[]): string | null {
		if (commits.length === 0) {
			return null;
		}

		const parts: string[] = [];

		parts.push('## Commit History');
		parts.push('');

		commits.forEach((commit) => {
			const shortSha = commit.sha.substring(0, 7);
			const timestamp = commit.timestamp
				? ` (${new Date(commit.timestamp).toISOString()})`
				: '';
			const author = commit.author ? ` by ${commit.author}` : '';

			parts.push(`- \`${shortSha}\` ${commit.message}${author}${timestamp}`);
		});

		parts.push('');
		parts.push(`**Total Commits**: ${commits.length}`);
		parts.push('');

		return parts.join('\n');
	}

	/**
	 * Format run metrics section
	 */
	private formatRunMetrics(options: PRBodyFormatterOptions): string | null {
		const { runStartTime, runEndTime, branchName, tag } = options;

		const hasMetrics = runStartTime || runEndTime || branchName || tag;

		if (!hasMetrics) {
			return null;
		}

		const parts: string[] = [];

		parts.push('## Run Metrics');
		parts.push('');

		// Duration
		if (runStartTime && runEndTime) {
			const duration = this.calculateDuration(runStartTime, runEndTime);
			parts.push(`- **Duration**: ${duration}`);
		} else if (runStartTime) {
			parts.push(`- **Started**: ${new Date(runStartTime).toISOString()}`);
		}

		// Branch
		if (branchName) {
			parts.push(`- **Branch**: \`${branchName}\``);
		}

		// Tag
		if (tag) {
			parts.push(`- **Tag**: \`${tag}\``);
		}

		parts.push('');

		return parts.join('\n');
	}

	/**
	 * Format links section
	 */
	private formatLinks(options: PRBodyFormatterOptions): string | null {
		const { taskId } = options;

		if (!taskId) {
			return null;
		}

		const parts: string[] = [];

		parts.push('## Related Links');
		parts.push('');
		parts.push(`- **Task ID**: \`${taskId}\``);

		// Task ID references (hyperlinks not yet implemented)

		parts.push('');

		return parts.join('\n');
	}

	/**
	 * Calculate duration between two timestamps
	 */
	private calculateDuration(startTime: string, endTime: string): string {
		const start = new Date(startTime).getTime();
		const end = new Date(endTime).getTime();
		if (Number.isNaN(start) || Number.isNaN(end)) {
			return 'duration unavailable';
		}
		const diffMs = end - start;
		if (diffMs < 0) {
			return 'duration unavailable';
		}

		const hours = Math.floor(diffMs / (1000 * 60 * 60));
		const minutes = Math.floor((diffMs % (1000 * 60 * 60)) / (1000 * 60));
		const seconds = Math.floor((diffMs % (1000 * 60)) / 1000);

		if (hours > 0) {
			return `${hours}h ${minutes}m ${seconds}s`;
		} else if (minutes > 0) {
			return `${minutes}m ${seconds}s`;
		} else {
			return `${seconds}s`;
		}
	}

	/**
	 * Format a minimal PR body (for quick PRs without full context)
	 */
	formatMinimal(options: {
		taskId?: string;
		taskTitle?: string;
		branchName?: string;
	}): string {
		const parts: string[] = [];

		parts.push('## Summary');
		parts.push('');

		if (options.taskTitle) {
			parts.push(options.taskTitle);
		} else {
			parts.push('Implementation changes for this task.');
		}

		parts.push('');

		if (options.taskId) {
			parts.push(`**Task ID**: \`${options.taskId}\``);
			parts.push('');
		}

		if (options.branchName) {
			parts.push(`**Branch**: \`${options.branchName}\``);
			parts.push('');
		}

		parts.push('---');
		parts.push('');
		parts.push('🤖 Generated by TaskMaster Autopilot');

		return parts.join('\n');
	}
}
